services:
  - type: web
    name: pengaduan-sekolah
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php artisan serve --host=0.0.0.0 --port=${PORT}"
    envVars:
      - key: APP_NAME
        value: "Pengaduan Sekolah"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:2fl+Ktvkfl+Fuz4Qp/A75G2RTiWVA/ZoKZvp6fiiM10="
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://pengaduan-sekolah.onrender.com"
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync